---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Register dev vpc and subnet in us-west-2
      ec2_vpc:
        state: present
        cidr_block: 10.0.0.0/16
        region: us-west-2
        resource_tags: { "Env":"Dev", "Name" : "taw" }

